first rewiew
KawaiiHarinezumi/stellar-burgers pull request #1
Opened 2024-08-28 23:29 UTC by KawaiiHarinezumi

2024-08-29 02:35 UTC, SergeyK2004 requested changes
Здравствуйте.
Работа проделана огромная

Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно. Почти весь заявленный функционал реализован. Здорово, что выделяется активная страница в главном меню. Бургер корректно собирается с возможностью менять ингредиенты местами.

Что нужно исправить:

* https://disk.yandex.ru/d/ZbHvD8TXiVCNdQ После авторизации, пользователя нужно переводить на главную страницу. Сейчас, если авторизация выполняется при попытке создания заказа неавторизованным пользователем, то пользователь оказывается на пустой странице.
* https://disk.yandex.ru/d/8OHu36ulDQyT6g При переходе на страницу заказа по прямой ссылке, заказ не открывается.
* https://disk.yandex.ru/d/1vzow6baMg1tHA Заголовок не соответствует макету. Необходимо отображать номер заказа.
* Так же обратите внимание, что в макете указано состояние заказа https://disk.yandex.ru/d/X54mRNqD-8Y41A, у вас его нет при отображении заказов.
* https://disk.yandex.ru/d/qXe5jixG3a47Mg Нужно центрировать контент на странице с деталями ингредиента. Обратите внимание, что при отображении страницы, у описания ингредента отсутствует заголовок, сверьтесь с макетом.

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.
Удачного рефакторинга кода.

2024-08-29 02:35 UTC, SergeyK2004 commented on src/components/app/app.tsx
> +      <Routes location={backgroundLocation || location}>
Отлично:
Отлично выполнено определение открытия модального окна или отдельной страницы.

2024-08-29 02:35 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +import { useDispatch, useSelector } from '../../services/store';
Отлично:
Правильно, что используете типизированные хуки

2024-08-29 02:35 UTC, SergeyK2004 commented on src/components/ui/app-header/app-header.tsx
> +          <NavLink
Отлично:
Здорово, что используете NavLink для главного меню

2024-08-29 02:35 UTC, SergeyK2004 commented on src/services/constructor/slice.ts
> +        const id = nanoid();
Отлично:
Хорошо, что вынесли работу с бибилиотекой в prepare

2024-08-31 22:43 UTC, KawaiiHarinezumi commented
Все ошибки исправлены (или я так считаю :D )

2024-09-01 17:53 UTC, SergeyK2004 approved these changes
Отлично. Замечаний больше нет.
Ваша работа принята. Желаю успехов в дальнейшем обучении.
Обратите внимание, что сейчас вам нужно смержить ветку review в main и после этого, при выполнении проектной работы следующего спринта создать новую ветку review, в которой вы будете покрывать приложение тестами.

2024-09-01 18:02 UTC, merged